### ISSUE TITLE
#2 on Mar 28th, 2017

### ISSUE THREAD

**Issue by ghost** [nodeschool/dusseldorf#2]
🕐 __Date__: March 28th, 2017, approx. 18:00 (6pm) - 22:00 (10pm)
🏠 __Venue__: InVision AG, Speditionstraße 5, Düsseldorf
💺 __Seats__: ~90
💬 __Mentors__: @pnn, @cilice, @addaleax, @Turncoat 

- [x] _recruit more mentors!_
- [x] create meetup
- [x] put it on the website
- [x] add it to nodeschool.io

**Comment by ghost** [comment]
### we are looking for mentors!

if you know node.js to _any_ degree (seriously, you don't need to be really good at it), like helping other people learn and have some free time on the 28th, you can volunteer as mentor! 

just comment on this issue saying that you'd like to be a mentor and we'll add you to the list!

**Comment by ghost** [comment]
here's a couple of things [every mentor should know](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)

**Comment by addaleax** [comment]
o/

**Comment by beckerei** [comment]
🖖
