### ISSUE TITLE
#3 on June 17th, 2017

### ISSUE THREAD

**Issue by ghost** [nodeschool/dusseldorf#3]
🕐 __Date__: June 17th, 2017, approx. 10:00 (10am) - 18:00 (6pm)
🏠 __Venue__: Hörsaal 5A, Heinrich-Heine Universität
💺 __Seats__: ~70
💬 __Mentors__: @pup, @addaleax, @ohcibi

- [x] create meetup
- [x] put it on the website
- [x] add it to nodeschool.io

**Comment by addaleax** [comment]
Just to be clear, it’s still a good idea to try and recruit complete newbies, right?

The last and this announcement sound like we’d primarily want to guide people through the workshoppers along a somewhat fixed schedule. Focusing on certain workshoppers seems okay to me, but I’d guess we can expect that we’re always going to have a lot of people who weren’t there for the previous event, so there’s always the possibility of just going and continuing to work on wherever one ended up the last time.

**Comment by addaleax** [comment]
@pup it has been pointed out to me that there is no date listed on https://nodeschool.io/dusseldorf/3, only on the RSVP link ;)

**Comment by ghost** [comment]
@addaleax yeah, this one's a special one, with the location and all, and as such, it's mainly focused on students

**Comment by addaleax** [comment]
Yeah, I had student newbies in mind, so… :smile_cat:

**Comment by ohcibi** [comment]
We won't restrict what workshoppers will be worked on but I'll prepare for the announced once only.

**Comment by ghost** [comment]
judging from the signups we have so far, it looks like there's mainly gonna be students, so i wouldn't be _that_ worried about them not understanding the basics of javascript, i guess? it's a fairly simple language to pick up and we can always redirect them to `javascripting`
